<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NCAAHoopsPool.com</title>
    <link href="style1.css" rel="stylesheet" type="text/css"/>
    <link rel="icon" type="image/x-icon" href="images/favicon.ico"/>
    <script src="_js/jquery-1.7.2.min.js"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-36422200-1"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-36422200-1');
	</script>

</head>