<head>
    <title>NCAAHoopsPool.com</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="style1.css" rel="stylesheet" type="text/css"/>
    
    <!--Google Analytics Code snippet-->
    <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-36422200-1']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
    </script>
    <script src="../_js/jquery-1.7.2.min.js"></script>
    <script>$(document).ready(function() {
        $('#listbelow :button').click(function() {
            alert ('You clicked on the Send Email to List Below button');
        });
    });
    </script>
</head>