-- SQL statements to create needed tables in existing PostgreSQL DB

CREATE TABLE games (
    id serial PRIMARY KEY,
    week_num smallint NOT NULL,
    gamedate date DEFAULT NULL,
    team_id smallint NOT NULL,
    opponent_id smallint DEFAULT NULL,
    tiebreaker smallint DEFAULT 0,
    tiebreakerpts smallint DEFAULT 0,
    locale smallint DEFAULT 0,
    outcome smallint DEFAULT 0
);

comment on column games.week_num is 'week # of game';
comment on column games.gamedate is 'date of game';
comment on column games.team_id is 'player team id';
comment on column games.opponent_id is 'game opponent team id';
comment on column games.tiebreaker is '=1 if game is tiebreaker game for week';
comment on column games.tiebreakerpts is '# actual total points for tiebreaker game';
comment on column games.locale is 'Value of 0-3 for No game, Home, Away, Neutral';
comment on column games.outcome is 'indicates winner of game (0=no decision; 1=Team; 2=Opponent)';

CREATE TABLE picks (
    id serial PRIMARY KEY,
    player_id smallint NOT NULL,
    game_id int NOT NULL,
    pick smallint DEFAULT 0,
    pick_result smallint DEFAULT 0,
    tiebreakerpts smallint DEFAULT 0
);

comment on column picks.player_id is 'reference to player table';
comment on column picks.game_id is 'reference to games table';
comment on column picks.pick is 'indicates picked winner of game (0=no pick; 1=Team; 2=Opponent)';
comment on column picks.pick_result is 'tracks whether pick is correct (1=correct, 0=wrong)';
comment on column picks.tiebreakerpts is '# total points selected for tiebreaker game';

CREATE TABLE player (
  id serial PRIMARY KEY,
  email varchar(50) NOT NULL,
  firstname varchar(50) NOT NULL,
  lastname varchar(50) NOT NULL,
  "password" varchar(255) DEFAULT NULL,
  team_id int NOT NULL,
  num_wins smallint DEFAULT 0,
  correct_picks smallint DEFAULT 0,
  wrong_picks smallint DEFAULT 0,
  createdate date NOT NULL,
  lastlogindate timestamp DEFAULT NULL
);

comment on column player.team_id is 'team that player selected';
comment on column player.num_wins is 'number of wins predicted for team selected';
comment on column player.correct_picks is 'overall correct # of games picked';
comment on column player.wrong_picks is 'overall incorrect # of games picked';


CREATE TABLE player_login (
  id serial PRIMARY KEY,
  player_id int NOT NULL,
  login_date timestamp NOT NULL
);

CREATE TABLE teams (
    id serial PRIMARY KEY,
    team_name varchar(255) NOT NULL,
    school varchar(255) NOT NULL,
    city varchar(50) NOT NULL,
    state varchar(50) NOT NULL,
    conference varchar(255) NOT NULL
);

CREATE TABLE weeks (
  id serial PRIMARY KEY,
  num smallint NOT NULL,
  "name" varchar(10) NOT NULL,
  from_date date NOT NULL,
  to_date date NOT NULL,
  deadline_date date NOT NULL,
  num_games smallint NOT NULL
);

comment on column weeks.from_date is 'date on which week of games begins, typically a Monday';
comment on column weeks.to_date is 'date on which week of games ends, typically a Sunday';
comment on column weeks.deadline_date is 'date by which players must submit picks, after this date Edit button hidden';
comment on column weeks.num_games is 'number of active games for week, calculated in games.php after admin updates games';


CREATE TABLE weeks_won (
  id serial PRIMARY KEY,
  week_id int NOT NULL,
  player_id int NOT NULL,
  week_correct_picks smallint DEFAULT 0,
  week_wrong_picks smallint DEFAULT 0,
  week_result smallint NOT NULL,
  money_result smallint DEFAULT 0
);

comment on column weeks_won.week_id is 'week num from weeks table';
comment on column weeks_won.player_id is 'played id from player table';
comment on column weeks_won.week_correct_picks is 'number of correct picks made that week';
comment on column weeks_won.week_wrong_picks is 'number of incorrect picks made that week';
comment on column weeks_won.week_result is 'Player result for week (0=lost, 1=won, 2=tied)';
comment on column weeks_won.money_result is 'if player won $ (1=won; 0=lost)';

CREATE TABLE winners (
  id serial PRIMARY KEY,
  week_id int NOT NULL,
  player_id int NOT NULL
);

comment on column winners.week_id is 'week num from weeks table';
comment on column winners.player_id is 'winner, id from player table';

-- INSERT DATA

INSERT INTO player (id, email, firstname, lastname, password, team_id, num_wins, correct_picks, wrong_picks, createdate, lastlogindate) VALUES
(0, 'admin', 'Pool', 'Administrator', '123456', 0, NULL, 0, 0, '2012-10-01', '2019-05-14 12:00:45');

INSERT INTO weeks (id, num, name, from_date, to_date, deadline_date, num_games) VALUES
(1, 1, 'Week 1', '2025-11-03', '2025-11-09', '2025-11-03', 0),
(2, 2, 'Week 2', '2025-11-10', '2025-11-16', '2025-11-10', 0),
(3, 3, 'Week 3', '2025-11-17', '2025-11-23', '2025-11-17', 0),
(4, 4, 'Week 4', '2025-11-24', '2025-11-30', '2025-11-24', 0),
(5, 5, 'Week 5', '2025-12-01', '2025-12-07', '2025-12-01', 0),
(6, 6, 'Week 6', '2025-12-08', '2025-12-14', '2025-12-08', 0),
(7, 7, 'Week 7', '2025-12-15', '2025-12-21', '2025-12-15', 0),
(8, 8, 'Week 8', '2025-12-22', '2025-12-28', '2025-12-22', 0),
(9, 9, 'Week 9', '2025-12-29', '2026-01-04', '2025-12-29', 0),
(10, 10, 'Week 10', '2026-01-05', '2026-01-11', '2026-01-05', 0),
(11, 11, 'Week 11', '2026-01-12', '2026-01-18', '2026-01-12', 0),
(12, 12, 'Week 12', '2026-01-19', '2026-01-25', '2026-01-19', 0),
(13, 13, 'Week 13', '2026-01-26', '2026-02-01', '2026-01-26', 0),
(14, 14, 'Week 14', '2026-02-02', '2026-02-08', '2026-02-02', 0),
(15, 15, 'Week 15', '2026-02-09', '2026-02-15', '2026-02-09', 0),
(16, 16, 'Week 16', '2026-02-16', '2026-02-22', '2026-02-16', 0),
(17, 17, 'Week 17', '2026-02-23', '2026-03-01', '2026-02-23', 0),
(18, 18, 'Week 18', '2026-03-02', '2026-03-08', '2026-03-02', 0);

INSERT INTO teams (id, team_name, school, city, state, conference) VALUES
(1, 'Lindenwood Lions (DII)', 'Lindenwood University', 'St. Charles', 'MO',  'Great Lakes Valley Conference'),
(2, 'Akron Zips', 'University of Akron', 'Akron', 'Ohio', 'Mid-American Conference'),
(3, 'Alabama Crimson Tide', 'University of Alabama', 'Tuscaloosa', 'Alabama', 'Southeastern Conference'),
(4, 'Alabama A&M Bulldogs', 'Alabama Agricultural and Mechanical University', 'Huntsville', 'Alabama', 'Southwestern Athletic Conference'),
(5, 'UAB Blazers', 'University of Alabama at Birmingham', 'Birmingham', 'Alabama', 'Conference USA'),
(6, 'Alabama State Hornets', 'Alabama State University', 'Montgomery', 'Alabama', 'Southwestern Athletic Conference'),
(7, 'Albany Great Danes', 'University at Albany, SUNY', 'Albany', 'New York', 'America East Conference'),
(8, 'Alcorn State Braves', 'Alcorn State University', 'Lorman', 'Mississippi', 'Southwestern Athletic Conference'),
(9, 'American Eagles', 'American University', 'Washington', 'District of Columbia', 'Patriot League'),
(10, 'Appalachian State Mountaineers', 'Appalachian State University', 'Boone', 'North Carolina', 'Southern Conference'),
(11, 'Arizona Wildcats', 'University of Arizona', 'Tucson', 'Arizona', 'Pacific-12 Conference'),
(12, 'Arizona State Sun Devils', 'Arizona State University', 'Tempe', 'Arizona', 'Pacific-12 Conference'),
(13, 'Arkansas Razorbacks', 'University of Arkansas', 'Fayetteville', 'Arkansas', 'Southeastern Conference'),
(14, 'Arkansas-Little Rock Trojans', 'University of Arkansas at Little Rock', 'Little Rock', 'Arkansas', 'Sun Belt Conference'),
(15, 'Arkansas-Pine Bluff Golden Lions', 'University of Arkansas at Pine Bluff', 'Pine Bluff', 'Arkansas', 'Southwestern Athletic Conference'),
(16, 'Arkansas State Red Wolves', 'Arkansas State University', 'Jonesboro', 'Arkansas', 'Sun Belt Conference'),
(17, 'Auburn Tigers', 'Auburn University', 'Auburn', 'Alabama', 'Southeastern Conference'),
(18, 'Austin Peay Governors', 'Austin Peay State University', 'Clarksville', 'Tennessee', 'Ohio Valley Conference'),
(19, 'Ball State Cardinals', 'Ball State University', 'Muncie', 'Indiana', 'Mid-American Conference'),
(20, 'Baylor Bears', 'Baylor University', 'Waco', 'Texas', 'Big 12 Conference'),
(21, 'Belmont Bruins', 'Belmont University', 'Nashville', 'Tennessee', 'Ohio Valley Conference'),
(22, 'Bethune-Cookman Wildcats', 'Bethune-Cookman University', 'Daytona Beach', 'Florida', 'Mid-Eastern Athletic Conference'),
(23, 'Binghamton Bearcats', 'Binghamton University', 'Vestal', 'New York', 'America East Conference'),
(24, 'Boise State Broncos', 'Boise State University', 'Boise', 'Idaho', 'Mountain West Conference'),
(25, 'Boston College Eagles', 'Boston College', 'Chestnut Hill', 'Massachusetts', 'Atlantic Coast Conference'),
(26, 'Boston University Terriers', 'Boston University', 'Boston', 'Massachusetts', 'America East Conference'),
(27, 'Bowling Green Falcons', 'Bowling Green State University', 'Bowling Green', 'Ohio', 'Mid-American Conference'),
(28, 'Bradley Braves', 'Bradley University', 'Peoria', 'Illinois', 'Missouri Valley Conference'),
(29, 'BYU Cougars', 'Brigham Young University', 'Provo', 'Utah', 'West Coast Conference'),
(30, 'Brown Bears', 'Brown University', 'Providence', 'Rhode Island', 'Ivy League'),
(31, 'Bryant Bulldogs', 'Bryant University', 'Smithfield', 'Rhode Island', 'Northeast Conference'),
(32, 'Bucknell Bison', 'Bucknell University', 'Lewisburg', 'Pennsylvania', 'Patriot League'),
(33, 'Buffalo Bulls', 'University at Buffalo, SUNY', 'Buffalo', 'New York', 'Mid-American Conference'),
(34, 'Butler Bulldogs', 'Butler University', 'Indianapolis', 'Indiana', 'Atlantic 10 Conference'),
(35, 'California Golden Bears', 'University of California, Berkeley', 'Berkeley', 'California', 'Pacific-12 Conference'),
(36, 'UC Davis Aggies', 'University of California, Davis', 'Davis', 'California', 'Big West Conference'),
(37, 'UC Irvine Anteaters', 'University of California, Irvine', 'Irvine', 'California', 'Big West Conference'),
(38, 'UCLA Bruins', 'University of California, Los Angeles', 'Los Angeles', 'California', 'Pacific-12 Conference'),
(39, 'Cal Poly Mustangs', 'California Polytechnic State University', 'San Luis Obispo', 'California', 'Big West Conference'),
(40, 'UC Riverside Highlanders', 'University of California, Riverside', 'Riverside', 'California', 'Big West Conference'),
(41, 'UC Santa Barbara Gauchos', 'University of California, Santa Barbara', 'Santa Barbara', 'California', 'Big West Conference'),
(42, 'Cal State Bakersfield Roadrunners', 'California State University, Bakersfield', 'Bakersfield', 'California', 'Independent'),
(43, 'Fresno State Bulldogs', 'California State University, Fresno', 'Fresno', 'California', 'Mountain West Conference'),
(44, 'Cal State Fullerton Titans', 'California State University, Fullerton', 'Fullerton', 'California', 'Big West Conference'),
(45, 'Long Beach State 49ers', 'California State University, Long Beach', 'Long Beach', 'California', 'Big West Conference'),
(46, 'Cal State Northridge Matadors', 'California State University, Northridge', 'Northridge, Los Angeles', 'California', 'Big West Conference'),
(47, 'Sacramento State Hornets', 'California State University, Sacramento', 'Sacramento', 'California', 'Big Sky Conference'),
(48, 'Campbell Fighting Camels', 'Campbell University', 'Buies Creek', 'North Carolina', 'Big South Conference'),
(49, 'Canisius Golden Griffins', 'Canisius College', 'Buffalo', 'New York', 'Metro Atlantic Athletic Conference'),
(50, 'Central Arkansas Bears', 'University of Central Arkansas', 'Conway', 'Arkansas', 'Southland Conference'),
(51, 'Central Connecticut State Blue Devils', 'Central Connecticut State University', 'New Britain', 'Connecticut', 'Northeast Conference'),
(52, 'UCF Knights', 'University of Central Florida', 'Orlando', 'Florida', 'Conference USA'),
(53, 'Central Michigan Chippewas', 'Central Michigan University', 'Mount Pleasant', 'Michigan', 'Mid-American Conference'),
(54, 'College of Charleston Cougars', 'College of Charleston', 'Charleston', 'South Carolina', 'Southern Conference'),
(55, 'Charleston Southern Buccaneers', 'Charleston Southern University', 'Charleston', 'South Carolina', 'Big South Conference'),
(56, 'Chicago State Cougars', 'Chicago State University', 'Chicago', 'Illinois', 'Great West Conference'),
(57, 'Cincinnati Bearcats', 'University of Cincinnati', 'Cincinnati', 'Ohio', 'Big East Conference'),
(58, 'The Citadel Bulldogs', 'The Citadel', 'Charleston', 'South Carolina', 'Southern Conference'),
(59, 'Clemson Tigers', 'Clemson University', 'Clemson', 'South Carolina', 'Atlantic Coast Conference'),
(60, 'Cleveland State Vikings', 'Cleveland State University', 'Cleveland', 'Ohio', 'Horizon League'),
(61, 'Coastal Carolina Chanticleers', 'Coastal Carolina University', 'Conway', 'South Carolina', 'Big South Conference'),
(62, 'Colgate Raiders', 'Colgate University', 'Hamilton', 'New York', 'Patriot League'),
(63, 'Colorado Buffaloes', 'University of Colorado at Boulder', 'Boulder', 'Colorado', 'Pacific-12 Conference'),
(64, 'Colorado State Rams', 'Colorado State University', 'Fort Collins', 'Colorado', 'Mountain West Conference'),
(65, 'Columbia Lions', 'Columbia University', 'Manhattan', 'New York', 'Ivy League'),
(66, 'Connecticut Huskies', 'University of Connecticut', 'Storrs', 'Connecticut', 'Big East Conference'),
(67, 'Coppin State Eagles', 'Coppin State University', 'Baltimore', 'Maryland', 'Mid-Eastern Athletic Conference'),
(68, 'Cornell Big Red', 'Cornell University', 'Ithaca', 'New York', 'Ivy League'),
(69, 'Creighton Bluejays', 'Creighton University', 'Omaha', 'Nebraska', 'Missouri Valley Conference'),
(70, 'Dartmouth Big Green', 'Dartmouth College', 'Hanover', 'New Hampshire', 'Ivy League'),
(71, 'Davidson Wildcats', 'Davidson College', 'Davidson', 'North Carolina', 'Southern Conference'),
(72, 'Dayton Flyers', 'University of Dayton', 'Dayton', 'Ohio', 'Atlantic 10 Conference'),
(73, 'Delaware Fightin'' Blue Hens', 'University of Delaware', 'Newark', 'Delaware', 'Colonial Athletic Association'),
(74, 'Delaware State Hornets', 'Delaware State University', 'Dover', 'Delaware', 'Mid-Eastern Athletic Conference'),
(75, 'Denver Pioneers', 'University of Denver', 'Denver', 'Colorado', 'Western Athletic Conference'),
(76, 'DePaul Blue Demons', 'DePaul University', 'Chicago', 'Illinois', 'Big East Conference'),
(77, 'Detroit Titans', 'University of Detroit Mercy', 'Detroit', 'Michigan', 'Horizon League'),
(78, 'Drake Bulldogs', 'Drake University', 'Des Moines', 'Iowa', 'Missouri Valley Conference'),
(79, 'Drexel Dragons', 'Drexel University', 'Philadelphia', 'Pennsylvania', 'Colonial Athletic Association'),
(80, 'Duke Blue Devils', 'Duke University', 'Durham', 'North Carolina', 'Atlantic Coast Conference'),
(81, 'Duquesne Dukes', 'Duquesne University', 'Pittsburgh', 'Pennsylvania', 'Atlantic 10 Conference'),
(82, 'East Carolina Pirates', 'East Carolina University', 'Greenville', 'North Carolina', 'Conference USA'),
(83, 'East Tennessee State Buccaneers', 'East Tennessee State University', 'Johnson City', 'Tennessee', 'Atlantic Sun Conference'),
(84, 'Eastern Illinois Panthers', 'Eastern Illinois University', 'Charleston', 'Illinois', 'Ohio Valley Conference'),
(85, 'Eastern Kentucky Colonels', 'Eastern Kentucky University', 'Richmond', 'Kentucky', 'Ohio Valley Conference'),
(86, 'Eastern Michigan Eagles', 'Eastern Michigan University', 'Ypsilanti', 'Michigan', 'Mid-American Conference'),
(87, 'Eastern Washington Eagles', 'Eastern Washington University', 'Cheney', 'Washington', 'Big Sky Conference'),
(88, 'Elon Phoenix', 'Elon University', 'Elon', 'North Carolina', 'Southern Conference'),
(89, 'Evansville Purple Aces', 'University of Evansville', 'Evansville', 'Indiana', 'Missouri Valley Conference'),
(90, 'Fairfield Stags', 'Fairfield University', 'Fairfield', 'Connecticut', 'Metro Atlantic Athletic Conference'),
(91, 'Fairleigh Dickinson Knights', 'Fairleigh Dickinson University', 'Hackensack', 'New Jersey', 'Northeast Conference'),
(92, 'Florida Gators', 'University of Florida', 'Gainesville', 'Florida', 'Southeastern Conference'),
(93, 'Florida A&M Rattlers', 'Florida Agricultural and Mechanical University', 'Tallahassee', 'Florida', 'Mid-Eastern Athletic Conference'),
(94, 'Florida Atlantic Owls', 'Florida Atlantic University', 'Boca Raton', 'Florida', 'Sun Belt Conference'),
(95, 'Florida Gulf Coast Eagles', 'Florida Gulf Coast University', 'Fort Myers', 'Florida', 'Atlantic Sun Conference'),
(96, 'FIU Panthers', 'Florida International University', 'Miami', 'Florida', 'Sun Belt Conference'),
(97, 'Florida State Seminoles', 'Florida State University', 'Tallahassee', 'Florida', 'Atlantic Coast Conference'),
(98, 'Fordham Rams', 'Fordham University', 'Bronx', 'New York', 'Atlantic 10 Conference'),
(99, 'Furman Paladins', 'Furman University', 'Greenville', 'South Carolina', 'Southern Conference'),
(100, 'Gardner-Webb Runnin Bulldogs', 'Gardner', 'Boiling Springs', 'North Carolina', 'Big South Conference'),
(101, 'George Mason Patriots', 'George Mason University', 'Fairfax', 'Virginia', 'Colonial Athletic Association'),
(102, 'George Washington Colonials', 'George Washington University', 'Washington', 'District of Columbia', 'Atlantic 10 Conference'),
(103, 'Georgetown Hoyas', 'Georgetown University', 'Washington', 'District of Columbia', 'Big East Conference'),
(104, 'Georgia Bulldogs', 'University of Georgia', 'Athens', 'Georgia', 'Southeastern Conference'),
(105, 'Georgia Tech Yellow Jackets', 'Georgia Institute of Technology', 'Atlanta', 'Georgia', 'Atlantic Coast Conference'),
(106, 'Georgia Southern Eagles', 'Georgia Southern University', 'Statesboro', 'Georgia', 'Southern Conference'),
(107, 'Georgia State Panthers', 'Georgia State University', 'Atlanta', 'Georgia', 'Colonial Athletic Association'),
(108, 'Gonzaga Bulldogs', 'Gonzaga University', 'Spokane', 'Washington', 'West Coast Conference'),
(109, 'Grambling State Tigers', 'Grambling State University', 'Grambling', 'Louisiana', 'Southwestern Athletic Conference'),
(110, 'Hampton Pirates', 'Hampton University', 'Hampton', 'Virginia', 'Mid-Eastern Athletic Conference'),
(111, 'Hartford Hawks', 'University of Hartford', 'West Hartford', 'Connecticut', 'America East Conference'),
(112, 'Harvard Crimson', 'Harvard University', 'Cambridge', 'Massachusetts', 'Ivy League'),
(113, 'Hawaii Rainbow Warriors', 'University of Hawai?i at M?noa', 'Honolulu', 'Hawaii', 'Big West Conference'),
(114, 'High Point Panthers', 'High Point University', 'High Point', 'North Carolina', 'Big South Conference'),
(115, 'Hofstra Pride', 'Hofstra University', 'Hempstead', 'New York', 'Colonial Athletic Association'),
(116, 'Holy Cross Crusaders', 'College of the Holy Cross', 'Worcester', 'Massachusetts', 'Patriot League'),
(117, 'Houston Cougars', 'University of Houston', 'Houston', 'Texas', 'Conference USA'),
(118, 'Houston Baptist Huskies', 'Houston Baptist University', 'Houston', 'Texas', 'Great West Conference'),
(119, 'Howard Bison', 'Howard University', 'Washington', 'District of Columbia', 'Mid-Eastern Athletic Conference'),
(120, 'Idaho Vandals', 'University of Idaho', 'Moscow', 'Idaho', 'Western Athletic Conference'),
(121, 'Idaho State Bengals', 'Idaho State University', 'Pocatello', 'Idaho', 'Big Sky Conference'),
(122, 'UIC Flames', 'University of Illinois at Chicago', 'Chicago', 'Illinois', 'Horizon League'),
(123, 'Illinois State Redbirds', 'Illinois State University', 'Normal', 'Illinois', 'Missouri Valley Conference'),
(124, 'Illinois Fighting Illini', 'University of Illinois at Urbana-Champaign', 'Urbana-Champaign', 'Illinois', 'Big Ten Conference'),
(125, 'Indiana State Sycamores', 'Indiana State University', 'Terre Haute', 'Indiana', 'Missouri Valley Conference'),
(126, 'Indiana Hoosiers', 'Indiana University', 'Bloomington', 'Indiana', 'Big Ten Conference'),
(127, 'IPFW Mastodons', 'Indiana University-Purdue University Fort Wayne', 'Fort Wayne', 'Indiana', 'The Summit League'),
(128, 'IUPUI Jaguars', 'Indiana University-Purdue University Indianapolis', 'Indianapolis', 'Indiana', 'The Summit League'),
(129, 'Iona Gaels', 'Iona College', 'New Rochelle', 'New York', 'Metro Atlantic Athletic Conference'),
(130, 'Iowa Hawkeyes', 'University of Iowa', 'Iowa City', 'Iowa', 'Big Ten Conference'),
(131, 'Iowa State Cyclones', 'Iowa State University', 'Ames', 'Iowa', 'Big 12 Conference'),
(132, 'Jackson State Tigers', 'Jackson State University', 'Jackson', 'Mississippi', 'Southwestern Athletic Conference'),
(133, 'Jacksonville State Gamecocks', 'Jacksonville State University', 'Jacksonville', 'Alabama', 'Ohio Valley Conference'),
(134, 'Jacksonville Dolphins', 'Jacksonville University', 'Jacksonville', 'Florida', 'Atlantic Sun Conference'),
(135, 'James Madison Dukes', 'James Madison University', 'Harrisonburg', 'Virginia', 'Colonial Athletic Association'),
(136, 'Kansas Jayhawks', 'University of Kansas', 'Lawrence', 'Kansas', 'Big 12 Conference'),
(137, 'Kansas State Wildcats', 'Kansas State University', 'Manhattan', 'Kansas', 'Big 12 Conference'),
(138, 'Kennesaw State Owls', 'Kennesaw State University', 'Kennesaw', 'Georgia', 'Atlantic Sun Conference'),
(139, 'Kent State Golden Flashes', 'Kent State University', 'Kent', 'Ohio', 'Mid-American Conference'),
(140, 'Kentucky Wildcats', 'University of Kentucky', 'Lexington', 'Kentucky', 'Southeastern Conference'),
(141, 'La Salle Explorers', 'La Salle University', 'Philadelphia', 'Pennsylvania', 'Atlantic 10 Conference'),
(142, 'Lafayette Leopards', 'Lafayette College', 'Easton', 'Pennsylvania', 'Patriot League'),
(143, 'Lamar Cardinals', 'Lamar University', 'Beaumont', 'Texas', 'Southland Conference'),
(144, 'Lehigh Mountain Hawks', 'Lehigh University', 'Bethlehem', 'Pennsylvania', 'Patriot League'),
(145, 'Liberty Flames', 'Liberty University', 'Lynchburg', 'Virginia', 'Big South Conference'),
(146, 'Lipscomb Bisons', 'Lipscomb University', 'Nashville', 'Tennessee', 'Atlantic Sun Conference'),
(147, 'Long Island Blackbirds', 'Long Island University-Brooklyn', 'Brooklyn', 'New York', 'Northeast Conference'),
(148, 'Longwood Lancers', 'Longwood University', 'Farmville', 'Virginia', 'Big South Conference'),
(149, 'Louisiana-Lafayette Ragin Cajuns', 'University of Louisiana at Lafayette', 'Lafayette', 'Louisiana', 'Sun Belt Conference'),
(150, 'Louisiana-Monroe Warhawks', 'University of Louisiana at Monroe', 'Monroe', 'Louisiana', 'Sun Belt Conference'),
(151, 'LSU Tigers', 'Louisiana State University', 'Baton Rouge', 'Louisiana', 'Southeastern Conference'),
(152, 'Louisiana Tech Bulldogs', 'Louisiana Tech University', 'Ruston', 'Louisiana', 'Western Athletic Conference'),
(153, 'Louisville Cardinals', 'University of Louisville', 'Louisville', 'Kentucky', 'Big East Conference'),
(154, 'Loyola Marymount Lions', 'Loyola Marymount University', 'Los Angeles', 'California', 'West Coast Conference'),
(155, 'Loyola Ramblers', 'Loyola University Chicago', 'Chicago', 'Illinois', 'Horizon League'),
(156, 'Loyola Greyhounds', 'Loyola University Maryland', 'Baltimore', 'Maryland', 'Metro Atlantic Athletic Conference'),
(157, 'Maine Black Bears', 'University of Maine', 'Orono', 'Maine', 'America East Conference'),
(158, 'Manhattan Jaspers', 'Manhattan College', 'Riverdale', 'New York', 'Metro Atlantic Athletic Conference'),
(159, 'Marist Red Foxes', 'Marist College', 'Poughkeepsie', 'New York', 'Metro Atlantic Athletic Conference'),
(160, 'Marquette Golden Eagles', 'Marquette University', 'Milwaukee', 'Wisconsin', 'Big East Conference'),
(161, 'Marshall Thundering Herd', 'Marshall University', 'Huntington', 'West Virginia', 'Conference USA'),
(162, 'UMBC Retrievers', 'University of Maryland, Baltimore County', 'Catonsville', 'Maryland', 'America East Conference'),
(163, 'Maryland Terrapins', 'University of Maryland, College Park', 'College Park', 'Maryland', 'Atlantic Coast Conference'),
(164, 'UMES Hawks', 'University of Maryland Eastern Shore', 'Princess Anne', 'Maryland', 'Mid-Eastern Athletic Conference'),
(165, 'Massachusetts Minutemen', 'University of Massachusetts Amherst', 'Amherst', 'Massachusetts', 'Atlantic 10 Conference'),
(166, 'McNeese State Cowboys', 'McNeese State University', 'Lake Charles', 'Louisiana', 'Southland Conference'),
(167, 'Memphis Tigers', 'University of Memphis', 'Memphis', 'Tennessee', 'Conference USA'),
(168, 'Mercer Bears', 'Mercer University', 'Macon', 'Georgia', 'Atlantic Sun Conference'),
(169, 'Miami Hurricanes', 'University of Miami', 'Coral Gables', 'Florida', 'Atlantic Coast Conference'),
(170, 'Miami RedHawks', 'Miami University', 'Oxford', 'Ohio', 'Mid-American Conference'),
(171, 'Michigan Wolverines', 'University of Michigan', 'Ann Arbor', 'Michigan', 'Big Ten Conference'),
(172, 'Michigan State Spartans', 'Michigan State University', 'East Lansing', 'Michigan', 'Big Ten Conference'),
(173, 'Middle Tennessee Blue Raiders', 'Middle Tennessee State University', 'Murfreesboro', 'Tennessee', 'Sun Belt Conference'),
(174, 'Minnesota Golden Gophers', 'University of Minnesota', 'Minneapolis-Saint Paul', 'Minnesota', 'Big Ten Conference'),
(175, 'Ole Miss Rebels', 'University of Mississippi', 'Oxford', 'Mississippi', 'Southeastern Conference'),
(176, 'Mississippi State Bulldogs', 'Mississippi State University', 'Starkville', 'Mississippi', 'Southeastern Conference'),
(177, 'Mississippi Valley State Delta Devils', 'Mississippi Valley State University', 'Itta Bena', 'Mississippi', 'Southwestern Athletic Conference'),
(178, 'Missouri Tigers', 'University of Missouri', 'Columbia', 'Missouri', 'Southeastern Conference'),
(179, 'UMKC Kangaroos', 'University of Missouri-Kansas City', 'Kansas City', 'Missouri', 'The Summit League'),
(180, 'Missouri State Bears', 'Missouri State University', 'Springfield', 'Missouri', 'Missouri Valley Conference'),
(181, 'Monmouth Hawks', 'Monmouth University', 'West Long Branch', 'New Jersey', 'Northeast Conference'),
(182, 'Montana Grizzlies', 'University of Montana', 'Missoula', 'Montana', 'Big Sky Conference'),
(183, 'Montana State Bobcats', 'Montana State University', 'Bozeman', 'Montana', 'Big Sky Conference'),
(184, 'Morehead State Eagles', 'Morehead State University', 'Morehead', 'Kentucky', 'Ohio Valley Conference'),
(185, 'Morgan State Bears', 'Morgan State University', 'Baltimore', 'Maryland', 'Mid-Eastern Athletic Conference'),
(186, 'Mount Saint Mary''s Mountaineers', 'Mount St. Mary''s University', 'Emmitsburg', 'Maryland', 'Northeast Conference'),
(187, 'Murray State Racers', 'Murray State University', 'Murray', 'Kentucky', 'Ohio Valley Conference'),
(188, 'Nebraska Cornhuskers', 'University of Nebraska-Lincoln', 'Lincoln', 'Nebraska', 'Big Ten Conference'),
(189, 'Nebraska-Omaha Mavericks', 'University of Nebraska at Omaha', 'Omaha', 'Nebraska', 'The Summit League'),
(190, 'UNLV Rebels', 'University of Nevada, Las Vegas', 'Paradise', 'Nevada', 'Mountain West Conference'),
(191, 'Nevada Wolf Pack', 'University of Nevada, Reno', 'Reno', 'Nevada', 'Mountain West Conference'),
(192, 'New Hampshire Wildcats', 'University of New Hampshire', 'Durham', 'New Hampshire', 'America East Conference'),
(193, 'NJIT Highlanders', 'New Jersey Institute of Technology', 'Newark', 'New Jersey', 'Great West Conference'),
(194, 'New Mexico Lobos', 'University of New Mexico', 'Albuquerque', 'New Mexico', 'Mountain West Conference'),
(195, 'New Mexico State Aggies', 'New Mexico State University', 'Las Cruces', 'New Mexico', 'Western Athletic Conference'),
(196, 'New Orleans Privateers', 'University of New Orleans', 'New Orleans', 'Louisiana', 'Independent'),
(197, 'Niagara Purple Eagles', 'Niagara University', 'Lewiston', 'New York', 'Metro Atlantic Athletic Conference'),
(198, 'Nicholls State Colonels', 'Nicholls State University', 'Thibodaux', 'Louisiana', 'Southland Conference'),
(199, 'Norfolk State Spartans', 'Norfolk State University', 'Norfolk', 'Virginia', 'Mid-Eastern Athletic Conference'),
(200, 'North Carolina A&T Aggies', 'North Carolina Agricultural and Technical State University', 'Greensboro', 'North Carolina', 'Mid-Eastern Athletic Conference'),
(201, 'UNC Asheville Bulldogs', 'University of North Carolina at Asheville', 'Asheville', 'North Carolina', 'Big South Conference'),
(202, 'North Carolina Central Eagles', 'North Carolina Central University', 'Durham', 'North Carolina', 'Mid-Eastern Athletic Conference'),
(203, 'North Carolina Tar Heels', 'University of North Carolina at Chapel Hill', 'Chapel Hill', 'North Carolina', 'Atlantic Coast Conference'),
(204, 'Charlotte 49ers', 'University of North Carolina at Charlotte', 'Charlotte', 'North Carolina', 'Atlantic 10 Conference'),
(205, 'UNC Greensboro Spartans', 'University of North Carolina at Greensboro', 'Greensboro', 'North Carolina', 'Southern Conference'),
(206, 'NC State Wolfpack', 'North Carolina State University', 'Raleigh', 'North Carolina', 'Atlantic Coast Conference'),
(207, 'UNC Wilmington Seahawks', 'University of North Carolina Wilmington', 'Wilmington', 'North Carolina', 'Colonial Athletic Association'),
(208, 'North Dakota', 'University of North Dakota', 'Grand Forks', 'North Dakota', 'Big Sky Conference'),
(209, 'North Dakota State Bison', 'North Dakota State University', 'Fargo', 'North Dakota', 'The Summit League'),
(210, 'North Florida Ospreys', 'University of North Florida', 'Jacksonville', 'Florida', 'Atlantic Sun Conference'),
(211, 'North Texas Mean Green', 'University of North Texas', 'Denton', 'Texas', 'Sun Belt Conference'),
(212, 'Northeastern Huskies', 'Northeastern University', 'Boston', 'Massachusetts', 'Colonial Athletic Association'),
(213, 'Northern Arizona Lumberjacks', 'Northern Arizona University', 'Flagstaff', 'Arizona', 'Big Sky Conference'),
(214, 'Northern Colorado Bears', 'University of Northern Colorado', 'Greeley', 'Colorado', 'Big Sky Conference'),
(215, 'Northern Illinois Huskies', 'Northern Illinois University', 'DeKalb', 'Illinois', 'Mid-American Conference'),
(216, 'Northern Iowa Panthers', 'University of Northern Iowa', 'Cedar Falls', 'Iowa', 'Missouri Valley Conference'),
(217, 'Northern Kentucky Norse', 'Northern Kentucky University', 'Highland Heights', 'Kentucky', 'Atlantic Sun Conference'),
(218, 'Northwestern State Demons', 'Northwestern State University', 'Natchitoches', 'Louisiana', 'Southland Conference'),
(219, 'Northwestern Wildcats', 'Northwestern University', 'Evanston', 'Illinois', 'Big Ten Conference'),
(220, 'Notre Dame Fighting Irish', 'University of Notre Dame', 'South Bend', 'Indiana', 'Big East Conference'),
(221, 'Oakland Golden Grizzlies', 'Oakland University', 'Rochester', 'Michigan', 'The Summit League'),
(222, 'Ohio State Buckeyes', 'Ohio State University', 'Columbus', 'Ohio', 'Big Ten Conference'),
(223, 'Ohio Bobcats', 'Ohio University', 'Athens', 'Ohio', 'Mid-American Conference'),
(224, 'Oklahoma Sooners', 'University of Oklahoma', 'Norman', 'Oklahoma', 'Big 12 Conference'),
(225, 'Oklahoma State Cowboys', 'Oklahoma State University-Stillwater', 'Stillwater', 'Oklahoma', 'Big 12 Conference'),
(226, 'Old Dominion Monarchs', 'Old Dominion University', 'Norfolk', 'Virginia', 'Colonial Athletic Association'),
(227, 'Oral Roberts Golden Eagles', 'Oral Roberts University', 'Tulsa', 'Oklahoma', 'Southland Conference'),
(228, 'Oregon Ducks', 'University of Oregon', 'Eugene', 'Oregon', 'Pacific-12 Conference'),
(229, 'Oregon State Beavers', 'Oregon State University', 'Corvallis', 'Oregon', 'Pacific-12 Conference'),
(230, 'Pacific Tigers', 'University of the Pacific', 'Stockton', 'California', 'Big West Conference'),
(231, 'Penn Quakers', 'University of Pennsylvania', 'Philadelphia', 'Pennsylvania', 'Ivy League'),
(232, 'Penn State Nittany Lions', 'Pennsylvania State University', 'State College', 'Pennsylvania', 'Big Ten Conference'),
(233, 'Pepperdine Waves', 'Pepperdine University', 'Malibu', 'California', 'West Coast Conference'),
(234, 'Pittsburgh Panthers', 'University of Pittsburgh', 'Pittsburgh', 'Pennsylvania', 'Big East Conference'),
(235, 'Portland Pilots', 'University of Portland', 'Portland', 'Oregon', 'West Coast Conference'),
(236, 'Portland State Vikings', 'Portland State University', 'Portland', 'Oregon', 'Big Sky Conference'),
(237, 'Prairie View A&M Panthers', 'Prairie View A&M University', 'Prairie View', 'Texas', 'Southwestern Athletic Conference'),
(238, 'Presbyterian Blue Hose', 'Presbyterian College', 'Clinton', 'South Carolina', 'Big South Conference'),
(239, 'Princeton Tigers', 'Princeton University', 'Princeton', 'New Jersey', 'Ivy League'),
(240, 'Providence Friars', 'Providence College', 'Providence', 'Rhode Island', 'Big East Conference'),
(241, 'Purdue Boilermakers', 'Purdue University', 'West Lafayette', 'Indiana', 'Big Ten Conference'),
(242, 'Quinnipiac Bobcats', 'Quinnipiac University', 'Hamden', 'Connecticut', 'Northeast Conference'),
(243, 'Radford Highlanders', 'Radford University', 'Radford', 'Virginia', 'Big South Conference'),
(244, 'Rhode Island Rams', 'University of Rhode Island', 'Kingston', 'Rhode Island', 'Atlantic 10 Conference'),
(245, 'Rice Owls', 'Rice University', 'Houston', 'Texas', 'Conference USA'),
(246, 'Richmond Spiders', 'University of Richmond', 'Richmond', 'Virginia', 'Atlantic 10 Conference'),
(247, 'Rider Broncs', 'Rider University', 'Lawrenceville', 'New Jersey', 'Metro Atlantic Athletic Conference'),
(248, 'Robert Morris Colonials', 'Robert Morris University', 'Moon Township', 'Pennsylvania', 'Northeast Conference'),
(249, 'Rutgers Scarlet Knights', 'Rutgers University', 'New Brunswick', 'New Jersey', 'Big East Conference'),
(250, 'Sacred Heart Pioneers', 'Sacred Heart University', 'Fairfield', 'Connecticut', 'Northeast Conference'),
(251, 'St. Bonaventure Bonnies', 'St. Bonaventure University', 'St. Bonaventure', 'New York', 'Atlantic 10 Conference'),
(252, 'St. Francis Terriers', 'St. Francis College', 'Brooklyn', 'New York', 'Northeast Conference'),
(253, 'Saint Francis Red Flash', 'Saint Francis University', 'Loretto', 'Pennsylvania', 'Northeast Conference'),
(254, 'St. John''s Red Storm', 'St. John''s University', 'Jamaica', 'New York', 'Big East Conference'),
(255, 'Saint Joseph''s Hawks', 'Saint Joseph''s University', 'Philadelphia', 'Pennsylvania', 'Atlantic 10 Conference'),
(256, 'Saint Louis Billikens', 'Saint Louis University', 'St. Louis', 'Missouri', 'Atlantic 10 Conference'),
(257, 'Saint Mary''s Gaels', 'Saint Mary''s College of California', 'Moraga', 'California', 'West Coast Conference'),
(258, 'Saint Peter''s Peacocks', 'Saint Peter''s College', 'Jersey City', 'New Jersey', 'Metro Atlantic Athletic Conference'),
(259, 'Sam Houston State Bearkats', 'Sam Houston State University', 'Huntsville', 'Texas', 'Southland Conference'),
(260, 'Samford Bulldogs', 'Samford University', 'Homewood', 'Alabama', 'Southern Conference'),
(261, 'San Diego Toreros', 'University of San Diego', 'San Diego', 'California', 'West Coast Conference'),
(262, 'San Diego State Aztecs', 'San Diego State University', 'San Diego', 'California', 'Mountain West Conference'),
(263, 'San Francisco Dons', 'University of San Francisco', 'San Francisco', 'California', 'West Coast Conference'),
(264, 'San Jose State Spartans', 'San Jose State University', 'San Jose', 'California', 'Western Athletic Conference'),
(265, 'Santa Clara Broncos', 'Santa Clara University', 'Santa Clara', 'California', 'West Coast Conference'),
(266, 'Savannah State Tigers', 'Savannah State University', 'Savannah', 'Georgia', 'Mid-Eastern Athletic Conference'),
(267, 'Seattle Redhawks', 'Seattle University', 'Seattle', 'Washington', 'Western Athletic Conference'),
(268, 'Seton Hall Pirates', 'Seton Hall University', 'South Orange', 'New Jersey', 'Big East Conference'),
(269, 'Siena Saints', 'Siena College', 'Loudonville', 'New York', 'Metro Atlantic Athletic Conference'),
(270, 'South Alabama Jaguars', 'University of South Alabama', 'Mobile', 'Alabama', 'Sun Belt Conference'),
(271, 'South Carolina Gamecocks', 'University of South Carolina', 'Columbia', 'South Carolina', 'Southeastern Conference'),
(272, 'South Carolina State Bulldogs', 'South Carolina State University', 'Orangeburg', 'South Carolina', 'Mid-Eastern Athletic Conference'),
(273, 'South Carolina Upstate Spartans', 'University of South Carolina Upstate', 'Spartanburg', 'South Carolina', 'Atlantic Sun Conference'),
(274, 'South Dakota Coyotes', 'University of South Dakota', 'Vermillion', 'South Dakota', 'The Summit League'),
(275, 'South Dakota State Jackrabbits', 'South Dakota State University', 'Brookings', 'South Dakota', 'The Summit League'),
(276, 'South Florida Bulls', 'University of South Florida', 'Tampa', 'Florida', 'Big East Conference'),
(277, 'Southeast Missouri Redhawks', 'Southeast Missouri State University', 'Cape Girardeau', 'Missouri', 'Ohio Valley Conference'),
(278, 'Southeastern Louisiana Lions', 'Southeastern Louisiana University', 'Hammond', 'Louisiana', 'Southland Conference'),
(279, 'USC Trojans', 'University of Southern California', 'Los Angeles', 'California', 'Pacific-12 Conference'),
(280, 'Southern Illinois Salukis', 'Southern Illinois University Carbondale', 'Carbondale', 'Illinois', 'Missouri Valley Conference'),
(281, 'SIU Edwardsville Cougars', 'Southern Illinois University Edwardsville', 'Edwardsville', 'Illinois', 'Ohio Valley Conference'),
(282, 'SMU Mustangs', 'Southern Methodist University', 'University Park', 'Texas', 'Conference USA'),
(283, 'Southern Miss Golden Eagles', 'University of Southern Mississippi', 'Hattiesburg', 'Mississippi', 'Conference USA'),
(284, 'Southern Jaguars', 'Southern University', 'Baton Rouge', 'Louisiana', 'Southwestern Athletic Conference'),
(285, 'Southern Utah Thunderbirds', 'Southern Utah University', 'Cedar City', 'Utah', 'Big Sky Conference'),
(286, 'Stanford Cardinal', 'Stanford University', 'Palo Alto', 'California', 'Pacific-12 Conference'),
(287, 'Stephen F. Austin Lumberjacks', 'Stephen F. Austin State University', 'Nacogdoches', 'Texas', 'Southland Conference'),
(288, 'Stetson Hatters', 'Stetson University', 'DeLand', 'Florida', 'Atlantic Sun Conference'),
(289, 'Stony Brook Seawolves', 'Stony Brook University', 'Stony Brook', 'New York', 'America East Conference'),
(290, 'Syracuse Orange', 'Syracuse University', 'Syracuse', 'New York', 'Big East Conference'),
(291, 'Temple Owls', 'Temple University', 'Philadelphia', 'Pennsylvania', 'Atlantic 10 Conference'),
(292, 'Tennessee Volunteers', 'University of Tennessee', 'Knoxville', 'Tennessee', 'Southeastern Conference'),
(293, 'Chattanooga Mocs', 'University of Tennessee at Chattanooga', 'Chattanooga', 'Tennessee', 'Southern Conference'),
(294, 'Tennessee-Martin Skyhawks', 'University of Tennessee at Martin', 'Martin', 'Tennessee', 'Ohio Valley Conference'),
(295, 'Tennessee State Tigers', 'Tennessee State University', 'Nashville', 'Tennessee', 'Ohio Valley Conference'),
(296, 'Tennessee Tech Golden Eagles', 'Tennessee Technological University', 'Cookeville', 'Tennessee', 'Ohio Valley Conference'),
(297, 'Texas A&M Aggies', 'Texas A&M University', 'College Station', 'Texas', 'Southeastern Conference'),
(298, 'Texas A&M-Corpus Christi Islanders', 'Texas A&M University', 'Corpus Christi', 'Texas', 'Southland Conference'),
(299, 'Texas-Arlington Mavericks', 'University of Texas at Arlington', 'Arlington', 'Texas', 'Western Athletic Conference'),
(300, 'Texas Longhorns', 'University of Texas at Austin', 'Austin', 'Texas', 'Big 12 Conference'),
(301, 'TCU Horned Frogs', 'Texas Christian University', 'Fort Worth', 'Texas', 'Big 12 Conference'),
(302, 'UTEP Miners', 'University of Texas at El Paso', 'El Paso', 'Texas', 'Conference USA'),
(303, 'UTPA Broncs', 'University of Texas-Pan American', 'Edinburg', 'Texas', 'Great West Conference'),
(304, 'UTSA Roadrunners', 'University of Texas at San Antonio', 'San Antonio', 'Texas', 'Western Athletic Conference'),
(305, 'Texas Southern Tigers', 'Texas Southern University', 'Houston', 'Texas', 'Southwestern Athletic Conference'),
(306, 'Texas State Bobcats', 'Texas State University-San Marcos', 'San Marcos', 'Texas', 'Western Athletic Conference'),
(307, 'Texas Tech Red Raiders', 'Texas Tech University', 'Lubbock', 'Texas', 'Big 12 Conference'),
(308, 'Toledo Rockets', 'University of Toledo', 'Toledo', 'Ohio', 'Mid-American Conference'),
(309, 'Towson Tigers', 'Towson University', 'Towson', 'Maryland', 'Colonial Athletic Association'),
(310, 'Troy Trojans', 'Troy University', 'Troy', 'Alabama', 'Sun Belt Conference'),
(311, 'Tulane Green Wave', 'Tulane University', 'New Orleans', 'Louisiana', 'Conference USA'),
(312, 'Tulsa Golden Hurricane', 'University of Tulsa', 'Tulsa', 'Oklahoma', 'Conference USA'),
(313, 'Air Force Falcons', 'United States Air Force Academy', 'Colorado Springs', 'Colorado', 'Mountain West Conference'),
(314, 'Army Black Knights', 'United States Military Academy', 'West Point', 'New York', 'Patriot League'),
(315, 'Navy Midshipmen', 'United States Naval Academy', 'Annapolis', 'Maryland', 'Patriot League'),
(316, 'Utah Utes', 'University of Utah', 'Salt Lake City', 'Utah', 'Pacific-12 Conference'),
(317, 'Utah State Aggies', 'Utah State University', 'Logan', 'Utah', 'Western Athletic Conference'),
(318, 'Utah Valley Wolverines', 'Utah Valley University', 'Orem', 'Utah', 'Great West Conference'),
(319, 'Valparaiso Crusaders', 'Valparaiso University', 'Valparaiso', 'Indiana', 'Horizon League'),
(320, 'Vanderbilt Commodores', 'Vanderbilt University', 'Nashville', 'Tennessee', 'Southeastern Conference'),
(321, 'Vermont Catamounts', 'University of Vermont', 'Burlington', 'Vermont', 'America East Conference'),
(322, 'Villanova Wildcats', 'Villanova University', 'Radnor Township', 'Pennsylvania', 'Big East Conference'),
(323, 'Virginia Cavaliers', 'University of Virginia', 'Charlottesville', 'Virginia', 'Atlantic Coast Conference'),
(324, 'VCU Rams', 'Virginia Commonwealth University', 'Richmond', 'Virginia', 'Atlantic 10 Conference'),
(325, 'VMI Keydets', 'Virginia Military Institute', 'Lexington', 'Virginia', 'Big South Conference'),
(326, 'Virginia Tech Hokies', 'Virginia Polytechnic Institute and State University', 'Blacksburg', 'Virginia', 'Atlantic Coast Conference'),
(327, 'Wagner Seahawks', 'Wagner College', 'Staten Island', 'New York', 'Northeast Conference'),
(328, 'Wake Forest Demon Deacons', 'Wake Forest University', 'Winston-Salem', 'North Carolina', 'Atlantic Coast Conference'),
(329, 'Washington Huskies', 'University of Washington', 'Seattle', 'Washington', 'Pacific-12 Conference'),
(330, 'Washington State Cougars', 'Washington State University', 'Pullman', 'Washington', 'Pacific-12 Conference'),
(331, 'Weber State Wildcats', 'Weber State University', 'Ogden', 'Utah', 'Big Sky Conference'),
(332, 'West Virginia Mountaineers', 'West Virginia University', 'Morgantown', 'West Virginia', 'Big 12 Conference'),
(333, 'Western Carolina Catamounts', 'Western Carolina University', 'Cullowhee', 'North Carolina', 'Southern Conference'),
(334, 'Western Illinois Leathernecks', 'Western Illinois University', 'Macomb', 'Illinois', 'The Summit League'),
(335, 'WKU Hilltoppers', 'Western Kentucky University', 'Bowling Green', 'Kentucky', 'Sun Belt Conference'),
(336, 'Western Michigan Broncos', 'Western Michigan University', 'Kalamazoo', 'Michigan', 'Mid-American Conference'),
(337, 'Wichita State Shockers', 'Wichita State University', 'Wichita', 'Kansas', 'Missouri Valley Conference'),
(338, 'William & Mary Tribe', 'College of William & Mary', 'Williamsburg', 'Virginia', 'Colonial Athletic Association'),
(339, 'Winthrop Eagles', 'Winthrop University', 'Rock Hill', 'South Carolina', 'Big South Conference'),
(340, 'Green Bay Phoenix', 'University of Wisconsin-Green Bay', 'Green Bay', 'Wisconsin', 'Horizon League'),
(341, 'Wisconsin Badgers', 'University of Wisconsin-Madison', 'Madison', 'Wisconsin', 'Big Ten Conference'),
(342, 'Milwaukee Panthers', 'University of Wisconsin-Milwaukee', 'Milwaukee', 'Wisconsin', 'Horizon League'),
(343, 'Wofford Terriers', 'Wofford College', 'Spartanburg', 'South Carolina', 'Southern Conference'),
(344, 'Wright State Raiders', 'Wright State University', 'Fairborn', 'Ohio', 'Horizon League'),
(345, 'Wyoming Cowboys', 'University of Wyoming', 'Laramie', 'Wyoming', 'Mountain West Conference'),
(346, 'Xavier Musketeers', 'Xavier University', 'Cincinnati', 'Ohio', 'Atlantic 10 Conference'),
(347, 'Yale Bulldogs', 'Yale University', 'New Haven', 'Connecticut', 'Ivy League'),
(348, 'Youngstown State Penguins', 'Youngstown State University', 'Youngstown', 'Ohio', 'Horizon League'),
(349, 'Chaminade Silverswords (DII)', 'Chaminade University', 'Honolulu', 'Hawaii', 'Pacific West'),
(350, 'Slippery Rock (DII)', 'Slippery Rock University', 'Slippery Rock', 'Pennsylvania', 'PA State Athletic Conference'),
(351, 'Tuskegee Golden Tigers (DII)', 'Tuskegee University', 'Tuskegee', 'Alabama', 'Southern Intercollegiate Athletic Conference'),
(352, 'La Verne Leopards (DIII)', 'La Verne University', 'La Verne', 'California', 'Southern California Intercollegiate Athletic Conference'),
(353, 'UMass Lowell RiverHawks', 'University of Massachusetts Lowell', 'Lowell', 'Massachusetts', 'America East Conference'),
(354, 'Emporia State Hornets', 'Emporia State University', 'Emporia', 'Kansas', 'Mid-America Intercollegiate Athletic Association'),
(355, 'St. Francis Brooklyn Terriers', 'St. Francis College', 'Brooklyn Heights', 'New York', 'Northeast Conference'),
(356, 'Tennessee Temple Crusaders', 'Tennessee Temple University', 'Chattanooga', 'Tennessee', 'Mid-East Conference'),
(357, 'Grand Canyon Antelopes', 'Grand Canyon University', 'Phoenix', 'Arizona', 'Western Athletic Conference'),
(358, 'UC San Diego Tritons', 'University of California, San Diego', 'San Diego', 'California', 'California Collegiate Athletic Association'),
(359, 'Seton Hill Griffins', 'Seton Hill University', 'Greensburg', 'Pennsylvania', 'Pennsylvania State Athletics Conference'),
(360, 'Rutgers-Newark Scarlet Raiders', 'Rutgers University-Newark', 'Newark', 'New Jersey', 'New Jersey Athletic Conference'),
(361, 'University of St. Thomas Tomcats', 'University of St. Thomas', 'St. Paul', 'Minnesota', 'Minnesota Intercollegiate Athletic Conference'),
(362, 'Fort Hays State Tigers', 'Fort Hays State', 'Hays', 'KS', 'Mid-America Intercollegiate Athletics Association'),
(363, 'Cal State East Bay Pioneers', 'Cal State East Bay', 'Hayward', 'CA', 'California Collegiate Athletic Association'),
(364, 'Life Pacific Warriors', 'Life Pacific College', 'San Dimas', 'CA', 'National Christian College Athletic Association'),
(365, 'Stockton Ospreys (DIII)', 'Stockton University', 'Galloway', 'NJ', 'Eastern Collegiate Athletic Conference'),
(366, 'Cal Baptist Lancers', 'California Baptist University', 'Riverside', 'CA', 'Western Athletic Conference'),
(367, 'Pacific Union Pioneers (NAIA)', 'Pacific Union College', 'Angwin',  'CA',  'California Pacific Conference'),
(368, 'Widener Pride (DIII)', 'Widener University', 'Chester', 'PA', 'Middle Atlantic Conference'),
(369, 'Tartleton Texans', 'Tartleton State University', 'Stephenville', 'TX', 'Western Athletic Conference'),
(370, 'Abilene Christian Wildcats', 'Abilene Christian University', 'Abilene', 'TX', 'Western Athletic Conference'),
(371, 'Utah Tech Trailblazers', 'Utah Tech University', 'St. George', 'UT', 'Western Athletic Conference'),
(372, 'Embry-Riddle Eagles (DII)', 'Embry-Riddle Aeronautical University', 'Daytona Beach', 'FL', 'Sunshine State Conference'),
(373, 'Wilkes University Colonels (DIII)', 'Wilkes University', 'Wilkes-Barre', 'PA', 'Middle Atlantic Conference'),
(374, 'TX A&M-Commerce Lions', 'Texas A&M University-Commerce', 'Commerce', 'TX', 'Southland Conference'),
(375, 'Eastern Oregon Mountaineers (NAIA)', 'Eastern Oregon University', 'La Grande', 'OR', 'Cascade Collegiate Conference'),
(376, 'Roberts Wesleyan Redhawks (DII)', 'Roberts Wesleyan University', 'Rochester', 'NY', 'East Coast Conference'),
(377, 'FDU-Florham Devils (DIII)', 'Fairleigh Dickinson University-Florham', 'Madison', 'NJ', 'Middle Athletic Conference'),
(378, 'Mississippi University for Women Owls (DIII)', 'Mississippi University for Women', 'Columbus', 'MS', 'St Louis Intercollegiate Athletic Conference'),
(379, 'Le Moyne Dolphins', 'Le Moyne College', 'Syracuse', 'NY', 'Northeast Conference'),
(380, 'Stonehill Skyhawks', 'Stonehill College', 'Easton', 'MA', 'Northeast Conference'),
(381, 'Incarnate Word Cardinals', 'University of the Incarnate Word', 'San Antonio', 'TX', 'Southland Conference'),
(382, 'North Alabama Lions', 'University of North Alabama', 'Florence', 'AL', 'Atlantic Sun Conference'),
(383, 'Mercyhurst Lakers', 'Mercyhurst University', 'Erie', 'PA', 'Northeast Conference');